---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: content/home.md
  label: Home
- type: directory
  path: content/posts
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/projects
  label: Portfolio
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - ENV=staging
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: gridsome develop
