---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/home.md
  label: Home
- type: document
  path: content/diensten.md
  label: Diensten
- type: document
  path: content/contact.md
  label: Contact
- type: document
  path: content/over-corneel.md
  label: Over Corneel
- type: document
  path: content/algemene-voorwaarden.md
  label: Algemene voorwaarden
  match: "**/*"
- type: document
  path: content/privacyverklaring.md
  label: Privacyverklaring
  match: "**/*"
- type: document
  path: content/colofon.md
  label: Colofon
  match: "**/*"
- type: heading
  label: Blog
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Portfolio
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - ENV=staging
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv/src"
  instant_preview_command: gridsome develop
