---
label: Service
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: sort_order
  type: number
  label: Sort order
  description: ''
  default: 0
  required: true
  config:
    min: 0
    max: 
    step: 10
    required: true
- name: show_on_homepage
  type: boolean
  label: Show on homepage
- type: text
  name: seo_title
  label: SEO title
- type: textarea
  name: seo_description
  label: SEO description
pages:
- content/services/advies-en-ondersteuning.md
- content/services/content-management.md
- content/services/mobile-first.md
- content/services/vindbaarheid-seo.md
- content/services/web-development.md
- content/services/webdesign.md
