---
label: Service
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: seo_title
  label: seo_title
- type: textarea
  name: seo_description
  label: seo_description
pages:
- content/services/advies-en-ondersteuning.md
- content/services/content-management.md
- content/services/mobile-first.md
- content/services/vindbaarheid-seo.md
- content/services/web-development.md
- content/services/webdesign.md
